FROM debian:stable-slim

ARG prism_version="4.10.1"

# Setup Basics

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get --no-install-recommends install -y \
    git \
    maven \ 
    openjdk-21-jre \
    python3 \
    python3-pip \
    python3-venv \
    wget \
    && apt-get clean

# Setup EvoChecker

WORKDIR /opt

RUN --mount=type=cache,target=/root/.m2 \
    git clone https://github.com/gerasimou/EvoChecker.git EvoChecker \
    && cd EvoChecker \
    && mvn install

# Setup PRISM

RUN ARCH=$(uname -m) && \
    case "$ARCH" in \
    x86_64) PRISM_ARCH="x86" ;; \
    aarch64) PRISM_ARCH="arm" ;;\
    esac \
    && wget -q -O - https://www.prismmodelchecker.org/dl/prism-${prism_version}-linux64-$PRISM_ARCH.tar.gz | tar -xzf - -C /opt \
    && mv /opt/prism-* /opt/prism \
    && cd /opt/prism \
    && /opt/prism/install.sh \
    && ln -s /opt/prism/bin/prism /usr/local/bin/prism \
    && ln -s /opt/prism/bin/xprism /usr/local/bin/xprism \
    && ln -s /opt/prism/bin/ngprism /usr/local/bin/ngprism \
    && echo 'export PATH=${PATH}:/opt/prism/bin' >> ~/.bashrc \
    && ln -s "$(which python3)" /usr/bin/python


# Setup PARLEY

WORKDIR /opt/PARLEY
COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m venv .venv \
    && .venv/bin/pip install -r requirements.txt

# TODO import rest of PARLEY and Setup experiment structure